apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-flask-example
  labels:
    app: vault-flask-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault-flask-example
  template:
    metadata:
      labels:
        app: vault-flask-example
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/role: "vault-flask-example"
        vault.hashicorp.com/agent-inject-secret-foo: "secret/data/foo"
        vault.hashicorp.com/secret-volume-path-foo: "/etc/secret-volume"
        vault.hashicorp.com/agent-inject-secret-bar: "secret/data/bar"
        vault.hashicorp.com/agent-inject-template-bar: |
          {{ with secret "secret/data/bar" -}}
            export BAR="{{ .Data.data.key }}"
          {{- end }}
    spec:
      serviceAccountName: vault-flask-example
      automountServiceAccountToken: true
      containers:
      - name: vault-flask-example
        image: assareh/vault-flask-example:0.0.1
        args: ["sh", "-c", "source /vault/secrets/bar && python3 application.py"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: vault-flask-example
spec:
  type: NodePort
  selector:
    app: vault-flask-example
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 5000
      targetPort: 5000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30001
---
